// ui/src/components/history.tsx
import { formatTime, getRelativeTimeString } from "@/lib/format-time";
import type { HistoryEntry, JobType } from "@/types/inspect";
import { useQuery, type UseMutationResult } from "@tanstack/react-query";
import clsx from "clsx";
import { ChevronDown, ListEnd, Trash } from "lucide-react";
import { useLocalStorage } from "@uidotdev/usehooks";
import { Button } from "./ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "./ui/dropdown-menu";
import { useRemoveHistoryEntryMutation } from "@/lib/commands";
import { SafeImage } from "./safe-image";

export function History({
  mutation,
}: {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  mutation: UseMutationResult<any, Error, [JobType, string, number], unknown>;
}) {
  const [open, setOpen] = useLocalStorage("historyOpen", false);
  return (
    <div>
      <button
        type="button"
        className="flex w-full justify-between items-center select-none cursor-pointer group text-left"
        onClick={() => setOpen((open) => !open)}
      >
        <h1 className="text-lg font-semibold mb-1 tracking-tight group-hover:underline">
          History
        </h1>
        <ChevronDown
          className={clsx(open && "rotate-180", "size-4 transition")}
        />
      </button>
      {open && (
        <div className="flex flex-col gap-2">
          <HistoryContainer mutation={mutation} />
        </div>
      )}
    </div>
  );
}

function HistoryContainer({
  mutation,
}: {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  mutation: UseMutationResult<any, Error, [JobType, string, number], unknown>;
}) {
  const { data } = useQuery({
    queryKey: ["history"],
    queryFn: () =>
      fetch("/api/history")
        .then((res) => res.json())
        .then((data) => data as HistoryEntry[]),
  });
  const removeHistoryMutation = useRemoveHistoryEntryMutation();
  if (data) {
    return data.map((entry) => (
      <div
        key={`${entry.webpage_url}-${entry.inserted_at}`}
        className="flex items-center border rounded-md overflow-hidden gap-2 bg-white select-none"
      >
        <div className="w-36 min-h-20 self-stretch relative flex bg-muted">
          <SafeImage
            src={entry.thumbnail}
            className="h-full object-cover bg-muted"
          />

          <p className="absolute right-1 bottom-1 text-xs text-white/80 border border-black/20 rounded-sm px-0.5 bg-black/50 ">
            {formatTime(entry.duration)}
          </p>
        </div>
        <div className="flex-1 py-3 pl-1">
          <p className="leading-5 mb-0.5 line-clamp-2 ">{entry.title}</p>
          <p className="text-muted-foreground text-sm mb-0.5">
            {entry.channel}
          </p>
          <p className="text-xs text-muted-foreground">
            Played {getRelativeTimeString(entry.inserted_at)}
          </p>
        </div>
        <div className="self-start">
          <DropdownMenu>
            <DropdownMenuTrigger
              render={
                <Button variant="ghost" size="icon" className="size-8">
                  <ChevronDown />
                </Button>
              }
            />
            <DropdownMenuContent align="end" className="w-max min-w-max">
              <DropdownMenuItem
                className="whitespace-nowrap"
                onClick={() =>
                  mutation.mutate([
                    entry.job_type,
                    entry.webpage_url,
                    entry.height ?? 720,
                  ])
                }
              >
                <ListEnd className="mr-1" />
                Add to queue
              </DropdownMenuItem>
              <DropdownMenuItem
                variant="destructive"
                className="whitespace-nowrap"
                onClick={() => removeHistoryMutation.mutate(entry.webpage_url)}
              >
                <Trash className="mr-1" />
                Remove entry
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </div>
    ));
  } else {
    return null;
  }
}

// ui-svelte/src/lib/components/History.svelte
<script lang="ts">
	import { formatTime, getRelativeTimeString } from '$lib/format-time';
	import type { HistoryEntry, JobType } from '$lib/types';
	import { buttonVariants } from '$lib/components/ui/button/index.js';
	import * as DropdownMenu from '$lib/components/ui/dropdown-menu/index.js';
	import { ChevronDown, ListEnd, Trash } from '@lucide/svelte';
	import SafeImage from './SafeImage.svelte';

	type Props = {
		open: boolean;
		entries: HistoryEntry[] | null;
		onToggle: () => void;
		onQueue: (jobType: JobType, url: string, height: number) => Promise<void> | void;
		onRemove: (url: string) => Promise<void> | void;
		onError: (message: string) => void;
	};

	let { open, entries, onToggle, onQueue, onRemove, onError }: Props = $props();

	async function run(action: () => Promise<void> | void) {
		try {
			await action();
		} catch (error) {
			onError(error instanceof Error ? error.message : 'History action failed');
		}
	}
</script>

<div>
	<button
		type="button"
		class="group flex w-full cursor-pointer items-center justify-between text-left select-none"
		onclick={onToggle}
	>
		<h1 class="mb-1 text-lg font-semibold tracking-tight group-hover:underline">History</h1>
		<ChevronDown class="size-4 transition {open ? 'rotate-180' : ''}" />
	</button>
	{#if open}
		<div class="flex flex-col gap-2">
			{#if entries}
				{#each entries as entry (`${entry.webpage_url}-${entry.inserted_at}`)}
					<div class="flex select-none items-center gap-2 overflow-hidden rounded-md border bg-white">
						<div class="relative flex min-h-20 w-36 self-stretch bg-muted">
							<SafeImage src={entry.thumbnail} class="h-full bg-muted object-cover" />
							<p class="absolute right-1 bottom-1 rounded-sm border border-black/20 bg-black/50 px-0.5 text-xs text-white/80">
								{formatTime(entry.duration)}
							</p>
						</div>
						<div class="flex-1 py-3 pl-1">
							<p class="mb-0.5 line-clamp-2 leading-5">{entry.title}</p>
							<p class="mb-0.5 text-sm text-muted-foreground">{entry.channel}</p>
							<p class="text-xs text-muted-foreground">Played {getRelativeTimeString(entry.inserted_at)}</p>
						</div>
						<div class="self-start">
							<DropdownMenu.Root>
								<DropdownMenu.Trigger class={`${buttonVariants({ variant: 'ghost', size: 'icon' })} size-8`} aria-label="Open history item menu">
									<ChevronDown />
								</DropdownMenu.Trigger>
								<DropdownMenu.Content align="end" class="w-max min-w-max">
									<DropdownMenu.Item class="whitespace-nowrap" onclick={() => run(() => onQueue(entry.job_type, entry.webpage_url, entry.height ?? 720))}>
										<ListEnd class="mr-1 size-4" /> Add to queue
									</DropdownMenu.Item>
									<DropdownMenu.Item variant="destructive" class="whitespace-nowrap" onclick={() => run(() => onRemove(entry.webpage_url))}>
										<Trash class="mr-1 size-4" /> Remove entry
									</DropdownMenu.Item>
								</DropdownMenu.Content>
							</DropdownMenu.Root>
						</div>
					</div>
				{/each}
			{:else}
				<p class="rounded-md border bg-white p-4 text-center text-sm text-muted-foreground">Loading history...</p>
			{/if}
		</div>
	{/if}
</div>
