// ui/src/components/player-progress.tsx
import { usePlayerCommandsMutation } from "@/lib/commands";
import type { PlayerState } from "@/types/inspect";
import { Volume1, Volume2, VolumeX } from "lucide-react";
import { useState, useEffect, useRef } from "react";
import { Button } from "./ui/button";
import { formatTime } from "@/lib/format-time";
import { Popover, PopoverContent, PopoverTrigger } from "./ui/popover";
import { Slider } from "./ui/slider";

export function PlayerProgress({
  playerState,
}: {
  playerState: PlayerState | null;
}) {
  const [shouldHide, setShouldHide] = useState(!playerState);

  useEffect(() => {
    if (!playerState) {
      // Small delay to allow fade-out before hiding
      const timeout = setTimeout(() => setShouldHide(true), 300);
      return () => clearTimeout(timeout);
    }
    // When playerState exists, clear the hide state immediately
    const timeout = setTimeout(() => setShouldHide(false), 0);
    return () => clearTimeout(timeout);
  }, [playerState]);

  const [isDragging, setIsDragging] = useState(false);
  const [dragTime, setDragTime] = useState<number | null>(null);
  const barRef = useRef<HTMLDivElement>(null);

  const { seekTo } = usePlayerCommandsMutation();

  const handlePointerDown = (e: React.PointerEvent) => {
    if (!playerState || !barRef.current) return;
    setIsDragging(true);
    barRef.current.setPointerCapture(e.pointerId);
    updateTimeFromPointer(e);
  };

  const handlePointerMove = (e: React.PointerEvent) => {
    if (!isDragging || !playerState || !barRef.current) return;
    updateTimeFromPointer(e);
  };

  const handlePointerUp = (e: React.PointerEvent) => {
    if (!playerState || !barRef.current) return;
    if (isDragging && dragTime !== null) {
      seekTo(dragTime);
    }
    setIsDragging(false);
    setDragTime(null);
    barRef.current.releasePointerCapture(e.pointerId);
  };

  const updateTimeFromPointer = (e: React.PointerEvent) => {
    if (!barRef.current || !playerState) return;
    const rect = barRef.current.getBoundingClientRect();
    const paddingX = 16; // px-4 = 1rem = 16px
    const usableWidth = rect.width - paddingX * 2;
    const offsetX = Math.min(
      Math.max(e.clientX - rect.left - paddingX, 0),
      usableWidth,
    );
    const percent = offsetX / usableWidth;
    const newTime = Math.round(percent * playerState.length);
    setDragTime(newTime);
  };

  const currentTime =
    isDragging && dragTime !== null ? dragTime : playerState?.time || 0;
  const progressPercent = (currentTime / (playerState?.length || 1)) * 100;

  const currString = formatTime(
    isDragging && dragTime !== null ? dragTime : playerState?.time || 0,
  );
  const totalString = playerState ? formatTime(playerState.length) : "";
  const volumePercent = playerState ? toVolumePercent(playerState.volume) : 0;

  return (
    <div
      className={`transition-opacity duration-300 ease-in-out ${
        playerState ? "opacity-100" : "opacity-0"
      } ${shouldHide ? "hidden" : "block"}`}
    >
      <div className="absolute bottom-0 left-0 w-full h-24 bg-linear-to-t from-black/70 to-black/0" />
      <div className="absolute bottom-6.5 left-0 pl-4">
        <p className="tracking-tight text-sm text-white/80 font-mono">
          <span>{currString}</span>
          <span className="mx-0.5">/</span>
          <span>{totalString}</span>
        </p>
      </div>
      <div className="absolute bottom-6.5 right-0 pr-4">
        <VolumeControl volumePercent={volumePercent} />
      </div>
      <div
        className="absolute bottom-1.5 left-0 w-full h-6 px-4 cursor-pointer touch-none"
        ref={barRef}
        onPointerDown={handlePointerDown}
        onPointerMove={handlePointerMove}
        onPointerUp={handlePointerUp}
      >
        <div className="relative h-full">
          <div className="bg-white/50 h-1 absolute left-0 top-1/2 -translate-y-1/2 w-full rounded-full"></div>
          <div
            className="bg-red-500 h-1 absolute left-0 top-1/2 -translate-y-1/2 rounded-full"
            style={{ width: `${progressPercent}%` }}
          ></div>
          <div
            className="absolute top-1/2 -translate-y-1/2 w-3 h-3 bg-red-500 rounded-full shadow"
            style={{
              left: `calc(${progressPercent}% - 6px)`, // 6px = half of 12px width
              transition: isDragging ? "none" : "left 0.1s linear",
              zIndex: 10,
            }}
          />
        </div>
      </div>
    </div>
  );
}

function toVolumePercent(volume: number) {
  const clampedVolume = Math.min(Math.max(volume, 0), 255);
  return Math.round((clampedVolume / 255) * 100);
}

function VolumeControl({ volumePercent }: { volumePercent: number }) {
  const { setVolume } = usePlayerCommandsMutation();
  const [isOpen, setIsOpen] = useState(false);
  const [localVolume, setLocalVolume] = useState<number | null>(null);
  const displayedVolume = localVolume ?? volumePercent;

  const handleOpenChange = (open: boolean) => {
    setIsOpen(open);
    if (open) {
      setLocalVolume(null);
    }
  };

  const handleVolumeChange = (value: number | readonly number[]) => {
    const nextVolume = Array.isArray(value) ? (value[0] ?? 0) : value;
    setLocalVolume(nextVolume);
    setVolume(nextVolume);
  };

  return (
    <Popover open={isOpen} onOpenChange={handleOpenChange}>
      <PopoverTrigger
        render={
          <Button
            aria-label={`Volume ${displayedVolume}%`}
            variant="ghost"
            size="icon-sm"
            className="cursor-pointer hover:bg-muted/15 aria-expanded:bg-transparent aria-expanded:hover:bg-muted/15"
          >
            {volumePercent === 0 ? (
              <VolumeX className="stroke-white/80" />
            ) : volumePercent <= 50 ? (
              <Volume1 className="stroke-white/80" />
            ) : (
              <Volume2 className="stroke-white/80" />
            )}
          </Button>
        }
      />
      <PopoverContent
        side="top"
        align="center"
        sideOffset={2}
        className="w-10 items-center px-1 py-2 bg-background/70 backdrop-blur-lg h-36 gap-1"
      >
        <span className="text-xs font-medium tabular-nums">
          {displayedVolume}%
        </span>
        <Slider
          aria-label="Volume"
          orientation="vertical"
          min={0}
          max={100}
          value={[displayedVolume]}
          onValueChange={handleVolumeChange}
          className="data-[orientation=vertical]:h-28"
        />
      </PopoverContent>
    </Popover>
  );
}

// ui-svelte/src/lib/components/PlayerProgress.svelte
<script lang="ts">
	import { executeCommand } from '$lib/api';
	import { formatTime } from '$lib/format-time';
	import type { PlayerState } from '$lib/types';
	import { buttonVariants } from '$lib/components/ui/button/index.js';
	import * as Popover from '$lib/components/ui/popover/index.js';
	import { Slider } from '$lib/components/ui/slider/index.js';
	import { Volume1, Volume2, VolumeX } from '@lucide/svelte';

	type Props = {
		playerState: PlayerState | null;
		onChanged: () => Promise<void> | void;
		onError: (message: string) => void;
	};

	let { playerState, onChanged, onError }: Props = $props();
	let isDragging = $state(false);
	let dragTime: number | null = $state(null);
	let barRef: HTMLDivElement | undefined = $state();
	let volumeOpen = $state(false);
	let localVolume: number | null = $state(null);

	let currentTime = $derived(isDragging && dragTime !== null ? dragTime : playerState?.time || 0);
	let progressPercent = $derived((currentTime / (playerState?.length || 1)) * 100);
	let currString = $derived(formatTime(currentTime));
	let totalString = $derived(playerState ? formatTime(playerState.length) : '');
	let volumePercent = $derived(playerState ? toVolumePercent(playerState.volume) : 0);
	let displayedVolume = $derived(localVolume ?? volumePercent);
	let volumeValue = $derived(displayedVolume);

	function toVolumePercent(volume: number) {
		const clampedVolume = Math.min(Math.max(volume, 0), 255);
		return Math.round((clampedVolume / 255) * 100);
	}

	function updateTimeFromPointer(event: PointerEvent) {
		if (!barRef || !playerState) return;
		const rect = barRef.getBoundingClientRect();
		const paddingX = 16;
		const usableWidth = rect.width - paddingX * 2;
		const offsetX = Math.min(Math.max(event.clientX - rect.left - paddingX, 0), usableWidth);
		dragTime = Math.round((offsetX / usableWidth) * playerState.length);
	}

	function handlePointerDown(event: PointerEvent) {
		if (!playerState || !barRef) return;
		isDragging = true;
		barRef.setPointerCapture(event.pointerId);
		updateTimeFromPointer(event);
	}

	function handlePointerMove(event: PointerEvent) {
		if (!isDragging || !playerState) return;
		updateTimeFromPointer(event);
	}

	async function handlePointerUp(event: PointerEvent) {
		if (!playerState || !barRef) return;
		try {
			if (isDragging && dragTime !== null) {
				await seekToTime(dragTime);
			}
		} catch (error) {
			onError(error instanceof Error ? error.message : 'Seek failed');
		} finally {
			isDragging = false;
			dragTime = null;
			barRef.releasePointerCapture(event.pointerId);
		}
	}

	async function seekToTime(time: number) {
		await executeCommand({ SeekTo: time });
		await onChanged();
	}

	async function handleSeekKeydown(event: KeyboardEvent) {
		if (!playerState) return;

		const step = 10;
		let nextTime: number | null = null;
		if (event.key === 'ArrowLeft') nextTime = Math.max(playerState.time - step, 0);
		if (event.key === 'ArrowRight') nextTime = Math.min(playerState.time + step, playerState.length);
		if (event.key === 'Home') nextTime = 0;
		if (event.key === 'End') nextTime = playerState.length;

		if (nextTime === null) return;
		event.preventDefault();
		try {
			await seekToTime(nextTime);
		} catch (error) {
			onError(error instanceof Error ? error.message : 'Seek failed');
		}
	}

	async function changeVolume(value: number) {
		localVolume = value;
		try {
			await executeCommand({ SetVolume: value });
			await onChanged();
		} catch (error) {
			onError(error instanceof Error ? error.message : 'Volume update failed');
		}
	}
</script>

{#if playerState}
	<div class="transition-opacity duration-300 ease-in-out">
		<div class="absolute bottom-0 left-0 h-24 w-full bg-linear-to-t from-black/70 to-black/0"></div>
		<div class="absolute bottom-6.5 left-0 pl-4">
			<p class="font-mono text-sm tracking-tight text-white/80">
				<span>{currString}</span><span class="mx-0.5">/</span><span>{totalString}</span>
			</p>
		</div>
		<div class="absolute right-0 bottom-6.5 pr-4">
			<Popover.Root bind:open={volumeOpen}>
				<Popover.Trigger aria-label={`Volume ${displayedVolume}%`} class={`${buttonVariants({ variant: 'ghost', size: 'icon-sm' })} cursor-pointer hover:bg-muted/15 aria-expanded:bg-transparent aria-expanded:hover:bg-muted/15`}>
					{#if volumePercent === 0}
						<VolumeX class="size-4 text-white/80" />
					{:else if volumePercent <= 50}
						<Volume1 class="size-4 text-white/80" />
					{:else}
						<Volume2 class="size-4 text-white/80" />
					{/if}
				</Popover.Trigger>
				<Popover.Content side="top" align="center" sideOffset={2} class="h-36 w-10 items-center gap-1 bg-background/70 px-1 py-2 backdrop-blur-lg">
					<span class="text-xs font-medium tabular-nums">{displayedVolume}%</span>
					<Slider
						aria-label="Volume"
						type="single"
						orientation="vertical"
						min={0}
						max={100}
						value={volumeValue}
						class="h-28"
						onValueCommit={(value: number) => changeVolume(value)}
					/>
				</Popover.Content>
			</Popover.Root>
		</div>
		<div
			class="absolute bottom-1.5 left-0 h-6 w-full cursor-pointer touch-none px-4"
			bind:this={barRef}
			role="slider"
			tabindex="0"
			aria-label="Playback position"
			aria-valuemin="0"
			aria-valuemax={playerState.length}
			aria-valuenow={currentTime}
			onkeydown={handleSeekKeydown}
			onpointerdown={handlePointerDown}
			onpointermove={handlePointerMove}
			onpointerup={handlePointerUp}
		>
			<div class="relative h-full">
				<div class="absolute top-1/2 left-0 h-1 w-full -translate-y-1/2 rounded-full bg-white/50"></div>
				<div
					class="absolute top-1/2 left-0 h-1 -translate-y-1/2 rounded-full bg-red-500"
					style={`width: ${progressPercent}%`}
				></div>
				<div
					class="absolute top-1/2 z-10 h-3 w-3 -translate-y-1/2 rounded-full bg-red-500 shadow"
					style={`left: calc(${progressPercent}% - 6px); transition: ${isDragging ? 'none' : 'left 0.1s linear'}`}
				></div>
			</div>
		</div>
	</div>
{/if}
