// ui/src/components/safe-image.tsx
import { type ImgHTMLAttributes, useState } from "react";

type SafeImageProps = Omit<ImgHTMLAttributes<HTMLImageElement>, "src"> & {
  src: string;
  fallbackSrc?: string;
};

export function SafeImage({ src, fallbackSrc, ...props }: SafeImageProps) {
  return (
    <SafeImageInner key={src} src={src} fallbackSrc={fallbackSrc} {...props} />
  );
}

function SafeImageInner({
  src,
  fallbackSrc,
  alt = "",
  onError,
  ...props
}: SafeImageProps) {
  const [useFallback, setUseFallback] = useState(false);
  const [hidden, setHidden] = useState(false);
  const currentSrc = useFallback && fallbackSrc ? fallbackSrc : src;

  if (hidden) return null;

  return (
    <img
      {...props}
      src={currentSrc}
      alt={alt}
      onError={(event) => {
        onError?.(event);

        if (fallbackSrc && !useFallback) {
          setUseFallback(true);
        } else {
          setHidden(true);
        }
      }}
    />
  );
}

// ui-svelte/src/lib/components/SafeImage.svelte
<script lang="ts">
	import type { HTMLImgAttributes } from 'svelte/elements';

	type Props = Omit<HTMLImgAttributes, 'src'> & {
		src: string;
		fallbackSrc?: string;
	};

	let { src, fallbackSrc, alt = '', ...rest }: Props = $props();
	let useFallback = $state(false);
	let hidden = $state(false);

	let currentSrc = $derived(useFallback && fallbackSrc ? fallbackSrc : src);

	function handleError() {
		if (fallbackSrc && !useFallback) {
			useFallback = true;
		} else {
			hidden = true;
		}
	}
</script>

{#if !hidden}
	<img src={currentSrc} {alt} onerror={handleError} {...rest} />
{/if}
